name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker build -t oas-changelog .
        docker tag oas-changelog docker.pkg.github.com/abdvl/oas-changelog/oas-changelog:$(date +%s)
        docker push docker.pkg.github.com/abdvl/oas-changelog/oas-changelog:$(date +%s)
